services:
  postgres:
    image: postgres:16
    container_name: tsis1_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: phonebook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata_tsis1:/var/lib/postgresql/data

volumes:
  pgdata_tsis1:
